CREATE ROLE erpqu_app LOGIN PASSWORD 'erpqu_app_dev_only';
GRANT CONNECT ON DATABASE management_system TO erpqu_app;
GRANT USAGE ON SCHEMA public TO erpqu_app;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO erpqu_app;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO erpqu_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO erpqu_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO erpqu_app;
