[package]
name = "management-system-commercial"
version = "0.1.0"
edition = "2021"

[dependencies]
management-system-core = { workspace = true }
sqlx = { workspace = true }
serde = { workspace = true }
chrono = { workspace = true }
rust_decimal = { workspace = true }
uuid = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
serde_json = { workspace = true }
utoipa = { workspace = true }
